#pragma once
#include "fl/Headers.h"

using namespace fl;
using namespace std;

class myFuzzy_02
{
private:
	Engine *engine_sugeno1;
	InputVariable* mDistance, *mOrientation, *moutput1, *mHeading;
	OutputVariable *output1_sugeno;

	void set_input1();
	void set_sugeno1();
public:
	void setInput();
	void get_sugeno(double distance, double orientation, double heading, double &output1);
};

void myFuzzy_02::setInput() {
	set_input1();
	set_sugeno1();
}

void myFuzzy_02::set_input1() {
	mDistance = new InputVariable;
	mDistance->setName("Distance");
	mDistance->setDescription("");
	mDistance->setEnabled(true);
	mDistance->setRange(0.000, 5.000);
	mDistance->setLockValueInRange(false);
	mDistance->addTerm(new Ramp("very_small", 1.25, 0));
	mDistance->addTerm(new Triangle("small", 0, 1.25, 2.5));
	mDistance->addTerm(new Triangle("medium", 1.25, 2.5, 3.75));
	mDistance->addTerm(new Triangle("big", 2.5, 3.75, 5));
	mDistance->addTerm(new Ramp("very_big", 3.75, 5));

	mOrientation = new InputVariable;
	mOrientation->setName("Orientation");
	mOrientation->setDescription("");
	mOrientation->setEnabled(true);
	mOrientation->setRange(-17.000, 17.000);
	mOrientation->setLockValueInRange(false);
	mOrientation->addTerm(new Ramp("negative_big", -11.33, -17));
	mOrientation->addTerm(new Triangle("negative_medium", -17, -11.33, -5.667));
	mOrientation->addTerm(new Triangle("negative_small", -11.33, -5.667, 0));
	mOrientation->addTerm(new Triangle("zero", -5.667, 0, 5.667));
	mOrientation->addTerm(new Triangle("positive_small", 0, 5.667, 11.33));
	mOrientation->addTerm(new Triangle("positive_medium", 5.667, 11.33, 17));
	mOrientation->addTerm(new Ramp("positive_big", 11.33, 17));

	mHeading = new InputVariable;
	mHeading->setName("Heading");
	mHeading->setDescription("");
	mHeading->setEnabled(true);
	mHeading->setRange(-180.000, 180.000);
	mHeading->setLockValueInRange(false);
	mHeading->addTerm(new Ramp("negative_front", -135, -180));
	mHeading->addTerm(new Triangle("front_left", -180, -135, -90));
	mHeading->addTerm(new Triangle("left", -135, -90, -45));
	mHeading->addTerm(new Triangle("back_left", -90, -45, 0));
	mHeading->addTerm(new Triangle("back", -45, 0, 45));
	mHeading->addTerm(new Triangle("back_right", 0, 45, 90));
	mHeading->addTerm(new Triangle("right", 45, 90, 135));
	mHeading->addTerm(new Triangle("front_right", 90, 135, 180));
	mHeading->addTerm(new Ramp("positive_front", 135, 180));

	output1_sugeno = new OutputVariable;
	output1_sugeno->setName("output");
	output1_sugeno->setDescription("");
	output1_sugeno->setEnabled(true);
	output1_sugeno->setRange(-1.000, 1.000);
	output1_sugeno->setLockValueInRange(false);
	output1_sugeno->setAggregation(new AlgebraicSum);
	output1_sugeno->setDefuzzifier(new WeightedAverage("TakagiSugeno"));
	output1_sugeno->setDefaultValue(0);
	output1_sugeno->setLockPreviousValue(false);
	output1_sugeno->addTerm(new Constant("left_handoff", -1));
	output1_sugeno->addTerm(new Constant("none", 0));
	output1_sugeno->addTerm(new Constant("right_handoff", 1));
};

void myFuzzy_02::get_sugeno(double distance, double orientation, double heading, double &output1) {

	mDistance->setValue(distance);
	mOrientation->setValue(orientation);
	mHeading->setValue(heading);
	engine_sugeno1->process();

	output1 = output1_sugeno->getValue();
};

void myFuzzy_02::set_sugeno1() {
	engine_sugeno1 = new Engine;
	engine_sugeno1->setName("Fuzzy1_sugeno");
	engine_sugeno1->setDescription("");

	engine_sugeno1->addInputVariable(mDistance);
	engine_sugeno1->addInputVariable(mOrientation);
	engine_sugeno1->addInputVariable(mHeading);
	engine_sugeno1->addOutputVariable(output1_sugeno);

	RuleBlock *ruleBlock = new RuleBlock;
	ruleBlock->setName("");
	ruleBlock->setDescription("");
	ruleBlock->setEnabled(true);
	ruleBlock->setConjunction(new Minimum);
	ruleBlock->setDisjunction(new Maximum);
	ruleBlock->setImplication(new AlgebraicProduct);
	ruleBlock->setActivation(new General);

	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_big) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_big) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_big) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_big) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_big) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_big) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_big) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_big) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_big) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_medium) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_medium) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_medium) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_medium) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_medium) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_medium) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_medium) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_medium) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_medium) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_small) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_small) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_small) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_small) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_small) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_small) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_small) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_small) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is negative_small) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is zero) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is zero) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is zero) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is zero) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is zero) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is zero) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is zero) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is zero) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is zero) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_small) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_small) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_small) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_small) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_small) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_small) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_small) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_small) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_small) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_medium) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_medium) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_medium) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_medium) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_medium) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_medium) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_medium) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_medium) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_medium) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_big) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_big) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_big) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_big) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_big) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_big) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_big) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_big) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_small) and (Orientation is positive_big) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_big) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_big) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_big) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_big) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_big) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_big) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_big) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_big) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_big) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_medium) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_medium) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_medium) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_medium) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_medium) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_medium) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_medium) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_medium) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_medium) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_small) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_small) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_small) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_small) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_small) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_small) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_small) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_small) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is negative_small) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is zero) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is zero) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is zero) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is zero) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is zero) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is zero) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is zero) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is zero) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is zero) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_small) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_small) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_small) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_small) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_small) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_small) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_small) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_small) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_small) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_medium) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_medium) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_medium) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_medium) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_medium) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_medium) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_medium) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_medium) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_medium) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_big) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_big) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_big) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_big) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_big) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_big) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_big) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_big) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is small) and (Orientation is positive_big) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_big) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_big) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_big) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_big) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_big) and (Heading is back) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_big) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_big) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_big) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_big) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_medium) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_medium) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_medium) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_medium) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_medium) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_medium) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_medium) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_medium) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_medium) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_small) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_small) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_small) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_small) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_small) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_small) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_small) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_small) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is negative_small) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is zero) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is zero) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is zero) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is zero) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is zero) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is zero) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is zero) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is zero) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is zero) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_small) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_small) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_small) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_small) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_small) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_small) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_small) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_small) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_small) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_medium) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_medium) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_medium) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_medium) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_medium) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_medium) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_medium) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_medium) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_medium) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_big) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_big) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_big) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_big) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_big) and (Heading is back) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_big) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_big) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_big) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is medium) and (Orientation is positive_big) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_big) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_big) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_big) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_big) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_big) and (Heading is back) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_big) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_big) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_big) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_big) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_medium) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_medium) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_medium) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_medium) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_medium) and (Heading is back) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_medium) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_medium) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_medium) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_medium) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_small) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_small) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_small) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_small) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_small) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_small) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_small) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_small) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is negative_small) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is zero) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is zero) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is zero) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is zero) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is zero) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is zero) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is zero) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is zero) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is zero) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_small) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_small) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_small) and (Heading is left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_small) and (Heading is back_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_small) and (Heading is back) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_small) and (Heading is back_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_small) and (Heading is right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_small) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_small) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_medium) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_medium) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_medium) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_medium) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_medium) and (Heading is back) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_medium) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_medium) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_medium) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_medium) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_big) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_big) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_big) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_big) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_big) and (Heading is back) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_big) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_big) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_big) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is big) and (Orientation is positive_big) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_big) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_big) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_big) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_big) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_big) and (Heading is back) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_big) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_big) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_big) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_big) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_medium) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_medium) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_medium) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_medium) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_medium) and (Heading is back) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_medium) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_medium) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_medium) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_medium) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_small) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_small) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_small) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_small) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_small) and (Heading is back) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_small) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_small) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_small) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is negative_small) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is zero) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is zero) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is zero) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is zero) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is zero) and (Heading is back) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is zero) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is zero) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is zero) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is zero) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_small) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_small) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_small) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_small) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_small) and (Heading is back) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_small) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_small) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_small) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_small) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_medium) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_medium) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_medium) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_medium) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_medium) and (Heading is back) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_medium) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_medium) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_medium) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_medium) and (Heading is positive_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_big) and (Heading is negative_front) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_big) and (Heading is front_left) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_big) and (Heading is left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_big) and (Heading is back_left) then output is left_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_big) and (Heading is back) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_big) and (Heading is back_right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_big) and (Heading is right) then output is right_handoff", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_big) and (Heading is front_right) then output is none", engine_sugeno1));
	ruleBlock->addRule(Rule::parse("if (Distance is very_big) and (Orientation is positive_big) and (Heading is positive_front) then output is none", engine_sugeno1));


	engine_sugeno1->addRuleBlock(ruleBlock);

	std::string status;
	if (not engine_sugeno1->isReady(&status))
		cout << "[engine_mamdani error] engine_mamdani is not ready:" << status << endl;
};


